=== BerniVila/xml/XML/Entrega_DTD_Bernardo_Vila_Ferrer_1DAWB/Resueltos_Berni/ediciones_aranda.dtd
<!ELEMENT ediciones_aranda (informe*)>
<!ELEMENT informe (cabecera, datos)>
<!ELEMENT cabecera (descripcion?, fecha)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT datos (region, region, region)>
<!ELEMENT region (trimestre, trimestre, trimestre, trimestre)>
<!ATTLIST region zona CDATA "">
<!ELEMENT trimestre (ventas?)>
<!ATTLIST trimestre num_trimestre (1 | 2 | 3 | 4) "4">
<!ELEMENT ventas (cantidad)>
<!ELEMENT cantidad (#PCDATA)>
<!-- Preguntar a pascual por el NO:INFO de la cantidad, si hay que usarlo como atributo forzosamente-->

=== BerniVila/xml/XML/Entrega_DTD_Bernardo_Vila_Ferrer_1DAWB/Resueltos_Berni/ediciones_aranda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ediciones_aranda SYSTEM "ediciones_aranda.dtd">

<ediciones_aranda>
  <informe>
    <cabecera>
      <descripcion>Informe de ventas para las regiones Norte, Centro y Sur</descripcion>
      <fecha>30/12/2009</fecha>
    </cabecera>
    <datos>
      <region zona="norte">
        <trimestre num_trimestre="1">
              <ventas cantidad="24000"/>
          </trimestre>
          <trimestre num_trimestre="2">
              <ventas cantidad="38600"/>
          </trimestre>
          <trimestre num_trimestre="3">
              <ventas cantidad="NO_INFO"/>
          </trimestre>
          <trimestre num_trimestre="4">
              <ventas cantidad="NO_INFO"/>
        </trimestre>
      </region>
      
      <region zona="centro">
        <trimestre num_trimestre="1">
            <ventas cantidad="NO_INFO"/>
        </trimestre>
        <trimestre num_trimestre="2">
            <ventas cantidad="16080"/>
        </trimestre>
        <trimestre num_trimestre="3">
            <ventas cantidad="25000"/>
        </trimestre>
        <trimestre num_trimestre="4">
            <ventas cantidad="29000"/>
        </trimestre>
      </region>
      
      <region zona="sur">
        <trimestre num_trimestre="1">
            <ventas cantidad="27000"/>
        </trimestre>
        <trimestre num_trimestre="2">
            <ventas cantidad="31400"/>
        </trimestre>
        <trimestre num_trimestre="3">
            <ventas cantidad="40100"/>
        </trimestre>
        <trimestre num_trimestre="4">
            <ventas cantidad="30000"/>
        </trimestre>
      </region>
    </datos>
  </informe>
</ediciones_aranda>
