<?xml version="1.0" encoding="ISO-8859-1"?>
<!--se sabe que el siempre tiene que existir al
menos un domicilio, y que el atributo tipo es obligatorio, y sólo puede tomar los valores o habitual-->
<!DOCTYPE matricula [
<!ELEMENT matricula (personal , pago)>
<!ELEMENT personal (dni , nombre , titulacion , curso_academico , domicilios)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (domicilio)+>
<!ELEMENT domicilio (nombre)>
<!ATTLIST domicilio tipo (habitual | familiar) "familiar">
<!ELEMENT pago (tipo_matricula)>
<!ELEMENT tipo_matricula (#PCDATA)>
]>
<matricula>
  <personal>
    <dni>99223366M</dni>
    <nombre>Juan Pardo Martín</nombre>
    <titulacion>Ingeniería Informática</titulacion>
    <curso_academico>1997/1998</curso_academico>
    <domicilios>
      <domicilio tipo="familiar">
        <nombre>C/ Principal no1</nombre>
      </domicilio>
      <domicilio tipo="habitual">
        <nombre>C/ Secundaria no2</nombre>
      </domicilio>
    </domicilios>
  </personal>
  <pago>
    <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
  </pago>
</matricula>
